#!/bin/bash
set -e

exeName=postTX
repoName=${exeName,,}
imgName=teamfae/$repoName

mkdir -p bin/
stack --local-bin-path $PWD/bin install --flag fae:static :$exeName
{ docker build -t $imgName . ; s=$?; } || true
rm -r ./bin
exit $s
